name: Sample Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MFEEDDOMAIN: bo.mfeeduno.com
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build App
        run: dotnet build -c Release --no-restore

      - name: Testing Echo
        run: echo "sed -i 's, localhost:44343, $MFEEDDOMAIN, g' src/MFeed/src/environments/environment.ts"
      